import { Piece } from "@/lib/types";

// Piece templates for creating new pieces
export const PIECE_PRESETS: Piece[] = [
  {
    id: 'K',
    name: "King",
    description: "Moves one square orthogonally or diagonally.",
    sprite: "king",
    moves: [
      {
        type: "slide",
        offset: [1, 0],
        canForward: true,
        canBackward: true,
        canSideways: true,
        range: {
          from: 1,
          to: 1,
        },
        canNonCapture: true,
        canCapture: true,
        isInitialOnly: false,
      },
      {
        type: "slide",
        offset: [1, 1],
        canForward: true,
        canBackward: true,
        canSideways: true,
        range: {
          from: 1,
          to: 1,
        },
        canNonCapture: true,
        canCapture: true,
        isInitialOnly: false,
      },
    ],
    promotions: [],
    isEnPassantTarget: false,
    isEnPassantCapturer: false,
  },
  {
    id: 'P',
    name: "Pawn",
    description: "Moves one square straight forward (except on its first move, when it may move two squares), but captures one square diagonally forward.",
    sprite: "pawn",
    moves: [
      {
        type: "slide",
        offset: [1, 0],
        range: {
          from: 1,
          to: 1,
        },
        canForward: true,
        canBackward: false,
        canSideways: false,
        canNonCapture: true,
        canCapture: false,
        isInitialOnly: false,
      },
      {
        type: "slide",
        offset: [1, 0],
        range: {
          from: 2,
          to: 2,
        },
        canForward: true,
        canBackward: false,
        canSideways: false,
        canNonCapture: true,
        canCapture: false,
        isInitialOnly: true,
      },
      {
        type: "slide",
        offset: [1, 1],
        range: {
          from: 1,
          to: 1,
        },
        canForward: true,
        canBackward: false,
        canSideways: true,
        canNonCapture: false,
        canCapture: true,
        isInitialOnly: false,
      },
    ],
    promotions: [{
      squares: [[0, 7], [1, 7], [2, 7], [3, 7], [4, 7], [5, 7], [6, 7], [7, 7]],
      becomes: ['n', 'b', 'r', 'q'],
    }],
    isEnPassantTarget: true,
    isEnPassantCapturer: true,
  },
  {
    id: 'N',
    name: "Knight",
    description: "Moves two squares in one direction (orthogonally) and then one square at a right angle to that direction.",
    sprite: "knight",
    moves: [
      {
        type: "leap",
        offset: [2, 1],
        range: {
          from: 1,
          to: 1,
        },
        canForward: true,
        canBackward: true,
        canSideways: true,
        canNonCapture: true,
        canCapture: true,
        isInitialOnly: false,
      },
    ],
    promotions: [],
    isEnPassantTarget: false,
    isEnPassantCapturer: false,
  },
  {
    id: 'B',
    name: "Bishop",
    description: "Moves diagonally across any number of squares.",
    sprite: "bishop",
    moves: [
      {
        type: "slide",
        offset: [1, 1],
        range: {
          from: 1,
          to: Infinity,
        },
        canForward: true,
        canBackward: true,
        canSideways: true,
        canNonCapture: true,
        canCapture: true,
        isInitialOnly: false,
      },
    ],
    promotions: [],
    isEnPassantTarget: false,
    isEnPassantCapturer: false,
  },
  {
    id: 'R',
    name: "Rook",
    description: "Moves orthogonally across any number of squares.",
    sprite: "rook",
    moves: [
      {
        type: "slide",
        offset: [1, 0],
        range: {
          from: 1,
          to: Infinity,
        },
        canForward: true,
        canBackward: true,
        canSideways: true,
        canNonCapture: true,
        canCapture: true,
        isInitialOnly: false,
      },
    ],
    promotions: [],
    isEnPassantTarget: false,
    isEnPassantCapturer: false,
  },
  {
    id: 'Q',
    name: "Queen",
    description: "Moves orthogonally or diagonally across any number of squares.",
    sprite: "queen",
    moves: [
      {
        type: "slide",
        offset: [1, 0],
        range: {
          from: 1,
          to: Infinity,
        },
        canForward: true,
        canBackward: true,
        canSideways: true,
        canNonCapture: true,
        canCapture: true,
        isInitialOnly: false,
      },
      {
        type: "slide",
        offset: [1, 1],
        range: {
          from: 1,
          to: Infinity,
        },
        canForward: true,
        canBackward: true,
        canSideways: true,
        canNonCapture: true,
        canCapture: true,
        isInitialOnly: false,
      },
    ],
    promotions: [],
    isEnPassantTarget: false,
    isEnPassantCapturer: false,
  },
  {
    id: 'H',
    name: "Archbishop",
    description: "Combines the power of the knight and bishop. (Also known as: Princess, Cardinal)",
    sprite: "archbis",
    moves: [
      {
        type: "slide",
        offset: [1, 1],
        range: {
          from: 1,
          to: Infinity,
        },
        canForward: true,
        canBackward: true,
        canSideways: true,
        canNonCapture: true,
        canCapture: true,
        isInitialOnly: false,
      },
      {
        type: "leap",
        offset: [2, 1],
        range: {
          from: 1,
          to: 1,
        },
        canForward: true,
        canBackward: true,
        canSideways: true,
        canNonCapture: true,
        canCapture: true,
        isInitialOnly: false,
      },
    ],
    promotions: [],
    isEnPassantTarget: false,
    isEnPassantCapturer: false,
  },
  {
    id: 'E',
    name: "Chancellor",
    description: "Combines the power of the knight and rook. (Also known as: Empress, Marshal)",
    sprite: "chancel",
    moves: [
      {
        type: "slide",
        offset: [1, 0],
        range: {
          from: 1,
          to: Infinity,
        },
        canForward: true,
        canBackward: true,
        canSideways: true,
        canNonCapture: true,
        canCapture: true,
        isInitialOnly: false,
      },
      {
        type: "leap",
        offset: [2, 1],
        range: {
          from: 1,
          to: 1,
        },
        canForward: true,
        canBackward: true,
        canSideways: true,
        canNonCapture: true,
        canCapture: true,
        isInitialOnly: false,
      },
    ],
    promotions: [],
    isEnPassantTarget: false,
    isEnPassantCapturer: false,
  },
  {
    id: 'A',
    name: "Amazon",
    description: "Combines the power of the knight and queen. (Also known as: Dragon)",
    sprite: "amazon",
    moves: [
      {
        type: "slide",
        offset: [1, 0],
        range: {
          from: 1,
          to: Infinity,
        },
        canForward: true,
        canBackward: true,
        canSideways: true,
        canNonCapture: true,
        canCapture: true,
        isInitialOnly: false,
      },
      {
        type: "slide",
        offset: [1, 1],
        range: {
          from: 1,
          to: Infinity,
        },
        canForward: true,
        canBackward: true,
        canSideways: true,
        canNonCapture: true,
        canCapture: true,
        isInitialOnly: false,
      },
      {
        type: "leap",
        offset: [2, 1],
        range: {
          from: 1,
          to: 1,
        },
        canForward: true,
        canBackward: true,
        canSideways: true,
        canNonCapture: true,
        canCapture: true,
        isInitialOnly: false,
      },
    ],
    promotions: [],
    isEnPassantTarget: false,
    isEnPassantCapturer: false,
  },
];